name: build release binaries

on:
  pull_request:
  push:

jobs:
  mecab:
    name: mecab
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gettext
      - uses: actions/checkout@v2
      - name: test mecab
        run: |
          ./autogen.sh
          ./configure
          make dist
          echo mecab-*.tar.gz
        working-directory: mecab
