name: build release binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gettext
      - uses: actions/checkout@v2
      - name: build mecab
        run: |
          ./autogen.sh
          ./configure
          make all
          sudo make install
          make dist
        working-directory: mecab
      - name: build ipadic
        run: |
          ./autogen.sh
          ./configure
          make dist
        working-directory: mecab-ipadic
      - name: build jumandic
        run: |
          ./autogen.sh
          ./configure
          make dist
        working-directory: mecab-jumandic
      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            mecab/mecab-*.tar.gz
            mecab-ipadic/mecab-ipadic-*.tar.gz
            mecab-jumandic/mecab-jumandic-*.tar.gz
