name: build release binaries

on: release

jobs:
  mecab:
    name: mecab
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gettext
      - uses: actions/checkout@v2
      - name: make dist
        run: |
          ./autogen.sh
          ./configure
          make dist
        working-directory: mecab
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.release.upload_url }}
          asset_path: mecab/mecab-0.996.tar.gz
          asset_name: mecab-0.996.tar.gz
          asset_content_type: application/octet-stream
