name: Test

on:
  pull_request: {}
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test mecab
        run: |
          ./configure
          make
          make check
          sudo make install
        working-directory: mecab
