name: Test

on:
  pull_request: {}
  push: {}

jobs:
  test-linux:
    name: test on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test mecab
        run: |
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
        working-directory: mecab

      - name: build ipadic euc-jp
        run: |
          ./configure
          make
          sudo make install
          make clean
        working-directory: mecab-ipadic

      - name: build ipadic shift-jis
        run: |
          ./configure --with-charset=sjis
          make
          sudo make install
          make clean
        working-directory: mecab-ipadic

      - name: build ipadic utf-8
        run: |
          ./configure --with-charset=utf8
          make
          sudo make install
          make clean
        working-directory: mecab-ipadic

      - name: build jumandic euc-jp
        run: |
          ./configure
          make
          sudo make install
          make clean
        working-directory: mecab-jumandic

      - name: build jumandic shift-jis
        run: |
          ./configure --with-charset=sjis
          make
          sudo make install
          make clean
        working-directory: mecab-jumandic

      - name: build jumandic utf-8
        run: |
          ./configure --with-charset=utf8
          make
          sudo make install
          make clean
        working-directory: mecab-jumandic

  test-linux-perl:
    name: test perl bindings
    strategy:
      matrix:
        perl:
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
    steps:
      - uses: actions/checkout@v2
      - name: install mecab
        run: |
          ./configure
          make
          sudo make install
          sudo ldconfig
        working-directory: mecab
      - name: install ipadic utf-8
        run: |
          ./configure --with-charset=utf8
          make
          sudo make install
        working-directory: mecab-ipadic
      - name: setup perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: build and test
        run: |
          perl Makefile.PL
          make
          make test
        working-directory: mecab/perl
