name: mecab on cygwin

on:
  pull_request:
    paths:
      - '.github/workflows/test-cygwin.yml'
      - 'mecab/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-cygwin.yml'
      - 'mecab/**'

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - run: git config --global core.autoCRLF false
      - uses: actions/checkout@v2
      - name: Install cygwin base packages with chocolatey
        run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
      - name: Install cygwin additional packages
        run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P autoconf,bison,gcc-core,make,libtoolize,aclocal,automake
        shell: cmd
      - name: Set ENV
        run: |
          echo '::set-env name=PATH::C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin'
      - name: Autoconf
        run: |
          bash.exe -c ./autogen.sh
          bash.exe -c ./configure
        shell: cmd
        working-directory: mecab
